apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: entity-crud
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # autoscaling.knative.dev/window: "10s"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/marianemuniz/entity-crud
          imagePullPolicy: Always